add_newline = false

format = "$directory$fill$git_branch$git_status$cmd_duration\n$character"

right_format = """$golang\
$rust\
$nodejs\
$python\
$ruby"""

[fill]
symbol = " "

[git_branch]
symbol = "\uf113"
format = "[$symbol $branch]($style) "

[git_status]
format = " [$all_status]($style)"
style = "red"
conflicted = "✖"
ahead = "⇡"
behind = "⇣"
stashed = ""
untracked = "?"
staged = "+"
modified = "!"
renamed = "»"
deleted = "✗"

[character]
format = "$symbol"
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
vicmd_symbol = "[❯](bold yellow) "
